// Mocks generated by Mockito 5.4.4 from annotations
// in tekushare/test/domain/usecases/walk/end_walk_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tekushare/domain/entities/walk_route.dart' as _i6;
import 'package:tekushare/domain/entities/walk_session.dart' as _i4;
import 'package:tekushare/domain/repositories/route_repository.dart' as _i5;
import 'package:tekushare/domain/repositories/walk_session_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WalkSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalkSessionRepository extends _i1.Mock
    implements _i2.WalkSessionRepository {
  MockWalkSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveSession(_i4.WalkSession? session) => (super.noSuchMethod(
        Invocation.method(
          #saveSession,
          [session],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.WalkSession>> getAllSessions() => (super.noSuchMethod(
        Invocation.method(
          #getAllSessions,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.WalkSession>>.value(<_i4.WalkSession>[]),
      ) as _i3.Future<List<_i4.WalkSession>>);

  @override
  _i3.Future<_i4.WalkSession?> getSessionById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSessionById,
          [id],
        ),
        returnValue: _i3.Future<_i4.WalkSession?>.value(),
      ) as _i3.Future<_i4.WalkSession?>);
}

/// A class which mocks [RouteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteRepository extends _i1.Mock implements _i5.RouteRepository {
  MockRouteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveRoute(_i6.WalkRoute? route) => (super.noSuchMethod(
        Invocation.method(
          #saveRoute,
          [route],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.WalkRoute?> getRouteBySessionId(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRouteBySessionId,
          [sessionId],
        ),
        returnValue: _i3.Future<_i6.WalkRoute?>.value(),
      ) as _i3.Future<_i6.WalkRoute?>);

  @override
  _i3.Future<List<_i6.WalkRoute>> getAllRoutes() => (super.noSuchMethod(
        Invocation.method(
          #getAllRoutes,
          [],
        ),
        returnValue: _i3.Future<List<_i6.WalkRoute>>.value(<_i6.WalkRoute>[]),
      ) as _i3.Future<List<_i6.WalkRoute>>);
}
