// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAqC1mYTIEmTByWYPh_1A556QteykqbUY',
    appId: '1:607979997790:web:369bb0b69d7d56025742cf',
    messagingSenderId: '607979997790',
    projectId: 'tekushare',
    authDomain: 'tekushare.firebaseapp.com',
    storageBucket: 'tekushare.firebasestorage.app',
    measurementId: 'G-7C2EDQW4J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDevgBcZY0-9VbJxibVTLuX5z3zUjsZBDk',
    appId: '1:607979997790:android:1d1f1528a392b6825742cf',
    messagingSenderId: '607979997790',
    projectId: 'tekushare',
    storageBucket: 'tekushare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTgxYc_oiALppqXOLdUQWY9BlL6fE5Cdk',
    appId: '1:607979997790:ios:ee2d0ae68448b7155742cf',
    messagingSenderId: '607979997790',
    projectId: 'tekushare',
    storageBucket: 'tekushare.firebasestorage.app',
    iosBundleId: 'com.example.tekushare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTgxYc_oiALppqXOLdUQWY9BlL6fE5Cdk',
    appId: '1:607979997790:ios:ee2d0ae68448b7155742cf',
    messagingSenderId: '607979997790',
    projectId: 'tekushare',
    storageBucket: 'tekushare.firebasestorage.app',
    iosBundleId: 'com.example.tekushare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAqC1mYTIEmTByWYPh_1A556QteykqbUY',
    appId: '1:607979997790:web:ea1b35f8244bb49a5742cf',
    messagingSenderId: '607979997790',
    projectId: 'tekushare',
    authDomain: 'tekushare.firebaseapp.com',
    storageBucket: 'tekushare.firebasestorage.app',
    measurementId: 'G-ZJ7797MYCK',
  );
}
