// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/saved_route_model.dart';
import 'data/models/spot_model.dart';
import 'data/models/walk_route_model.dart';
import 'data/models/walk_session_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7489605914726273475),
      name: 'SavedRouteModel',
      lastPropertyId: const obx_int.IdUid(8, 8503831499602420933),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2903911351368461518),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6038868310966606448),
            name: 'userUid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 1857520984652546542)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7997517541089110512),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 243568257568447536),
            name: 'date',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8705507653777122883),
            name: 'distance',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5213122988155261609),
            name: 'time',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7859650230451945715),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8503831499602420933),
            name: 'walkSessionId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 8481478283363595926),
      name: 'SpotModel',
      lastPropertyId: const obx_int.IdUid(10, 9142305711447235650),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2920357863814774842),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7204710948942407810),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(2, 3191489977635530073)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8471282771292118994),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7090024025017031088),
            name: 'latitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8861009369417351075),
            name: 'longitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6034721514288059866),
            name: 'statusName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1513058705711166904),
            name: 'memo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 148024176784313469),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7142488862004607575),
            name: 'photoPaths',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 9142305711447235650),
            name: 'createdAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 5788617943982370255),
      name: 'WalkRouteModel',
      lastPropertyId: const obx_int.IdUid(6, 5159250059236105716),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 732685086915125973),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 479241945827114914),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(3, 881151546691708027)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2874140942122530581),
            name: 'walkSessionId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(4, 7945588830789651940)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 164477172535919472),
            name: 'userUid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(5, 6692260172934188870)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3244908164062144619),
            name: 'pointsJson',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5159250059236105716),
            name: 'createdAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 7969674422863070264),
      name: 'WalkSessionModel',
      lastPropertyId: const obx_int.IdUid(7, 1415508175939701772),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4805055088879611507),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5044778078737198802),
            name: 'uid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(6, 1949058247438553960)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7486150492048852117),
            name: 'userUid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(7, 3475997624815909548)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2708160122215410577),
            name: 'statusName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4433423887378260953),
            name: 'startedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4990450389672713425),
            name: 'finishedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1415508175939701772),
            name: 'elapsedSeconds',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(4, 7969674422863070264),
      lastIndexId: const obx_int.IdUid(7, 3475997624815909548),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    SavedRouteModel: obx_int.EntityDefinition<SavedRouteModel>(
        model: _entities[0],
        toOneRelations: (SavedRouteModel object) => [],
        toManyRelations: (SavedRouteModel object) => {},
        getId: (SavedRouteModel object) => object.id,
        setId: (SavedRouteModel object, int id) {
          object.id = id;
        },
        objectToFB: (SavedRouteModel object, fb.Builder fbb) {
          final userUidOffset = fbb.writeString(object.userUid);
          final nameOffset = fbb.writeString(object.name);
          final dateOffset = fbb.writeString(object.date);
          final distanceOffset = fbb.writeString(object.distance);
          final timeOffset = fbb.writeString(object.time);
          final walkSessionIdOffset = object.walkSessionId == null
              ? null
              : fbb.writeString(object.walkSessionId!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userUidOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, dateOffset);
          fbb.addOffset(4, distanceOffset);
          fbb.addOffset(5, timeOffset);
          fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
          fbb.addOffset(7, walkSessionIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = SavedRouteModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..userUid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..date = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..distance = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..time = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0))
            ..walkSessionId = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18);

          return object;
        }),
    SpotModel: obx_int.EntityDefinition<SpotModel>(
        model: _entities[1],
        toOneRelations: (SpotModel object) => [],
        toManyRelations: (SpotModel object) => {},
        getId: (SpotModel object) => object.id,
        setId: (SpotModel object, int id) {
          object.id = id;
        },
        objectToFB: (SpotModel object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final titleOffset = fbb.writeString(object.title);
          final statusNameOffset = fbb.writeString(object.statusName);
          final memoOffset =
              object.memo == null ? null : fbb.writeString(object.memo!);
          final categoryOffset = object.category == null
              ? null
              : fbb.writeString(object.category!);
          final photoPathsOffset = fbb.writeList(
              object.photoPaths.map(fbb.writeString).toList(growable: false));
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addFloat64(3, object.latitude);
          fbb.addFloat64(4, object.longitude);
          fbb.addOffset(5, statusNameOffset);
          fbb.addOffset(6, memoOffset);
          fbb.addOffset(7, categoryOffset);
          fbb.addOffset(8, photoPathsOffset);
          fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = SpotModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..uid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..title = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..latitude =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..longitude =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..statusName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 14, '')
            ..memo = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16)
            ..category = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18)
            ..photoPaths = const fb.ListReader<String>(
                    fb.StringReader(asciiOptimization: true),
                    lazy: false)
                .vTableGet(buffer, rootOffset, 20, [])
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0));

          return object;
        }),
    WalkRouteModel: obx_int.EntityDefinition<WalkRouteModel>(
        model: _entities[2],
        toOneRelations: (WalkRouteModel object) => [],
        toManyRelations: (WalkRouteModel object) => {},
        getId: (WalkRouteModel object) => object.id,
        setId: (WalkRouteModel object, int id) {
          object.id = id;
        },
        objectToFB: (WalkRouteModel object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final walkSessionIdOffset = fbb.writeString(object.walkSessionId);
          final userUidOffset = fbb.writeString(object.userUid);
          final pointsJsonOffset = fbb.writeString(object.pointsJson);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, walkSessionIdOffset);
          fbb.addOffset(3, userUidOffset);
          fbb.addOffset(4, pointsJsonOffset);
          fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = WalkRouteModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..uid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..walkSessionId = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..userUid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..pointsJson = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));

          return object;
        }),
    WalkSessionModel: obx_int.EntityDefinition<WalkSessionModel>(
        model: _entities[3],
        toOneRelations: (WalkSessionModel object) => [],
        toManyRelations: (WalkSessionModel object) => {},
        getId: (WalkSessionModel object) => object.id,
        setId: (WalkSessionModel object, int id) {
          object.id = id;
        },
        objectToFB: (WalkSessionModel object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final userUidOffset = fbb.writeString(object.userUid);
          final statusNameOffset = fbb.writeString(object.statusName);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, userUidOffset);
          fbb.addOffset(3, statusNameOffset);
          fbb.addInt64(4, object.startedAt?.millisecondsSinceEpoch);
          fbb.addInt64(5, object.finishedAt?.millisecondsSinceEpoch);
          fbb.addInt64(6, object.elapsedSeconds);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final startedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 12);
          final finishedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 14);
          final object = WalkSessionModel()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..uid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..userUid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..statusName = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..startedAt = startedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(startedAtValue)
            ..finishedAt = finishedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(finishedAtValue)
            ..elapsedSeconds =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SavedRouteModel] entity fields to define ObjectBox queries.
class SavedRouteModel_ {
  /// See [SavedRouteModel.id].
  static final id =
      obx.QueryIntegerProperty<SavedRouteModel>(_entities[0].properties[0]);

  /// See [SavedRouteModel.userUid].
  static final userUid =
      obx.QueryStringProperty<SavedRouteModel>(_entities[0].properties[1]);

  /// See [SavedRouteModel.name].
  static final name =
      obx.QueryStringProperty<SavedRouteModel>(_entities[0].properties[2]);

  /// See [SavedRouteModel.date].
  static final date =
      obx.QueryStringProperty<SavedRouteModel>(_entities[0].properties[3]);

  /// See [SavedRouteModel.distance].
  static final distance =
      obx.QueryStringProperty<SavedRouteModel>(_entities[0].properties[4]);

  /// See [SavedRouteModel.time].
  static final time =
      obx.QueryStringProperty<SavedRouteModel>(_entities[0].properties[5]);

  /// See [SavedRouteModel.createdAt].
  static final createdAt =
      obx.QueryDateProperty<SavedRouteModel>(_entities[0].properties[6]);

  /// See [SavedRouteModel.walkSessionId].
  static final walkSessionId =
      obx.QueryStringProperty<SavedRouteModel>(_entities[0].properties[7]);
}

/// [SpotModel] entity fields to define ObjectBox queries.
class SpotModel_ {
  /// See [SpotModel.id].
  static final id =
      obx.QueryIntegerProperty<SpotModel>(_entities[1].properties[0]);

  /// See [SpotModel.uid].
  static final uid =
      obx.QueryStringProperty<SpotModel>(_entities[1].properties[1]);

  /// See [SpotModel.title].
  static final title =
      obx.QueryStringProperty<SpotModel>(_entities[1].properties[2]);

  /// See [SpotModel.latitude].
  static final latitude =
      obx.QueryDoubleProperty<SpotModel>(_entities[1].properties[3]);

  /// See [SpotModel.longitude].
  static final longitude =
      obx.QueryDoubleProperty<SpotModel>(_entities[1].properties[4]);

  /// See [SpotModel.statusName].
  static final statusName =
      obx.QueryStringProperty<SpotModel>(_entities[1].properties[5]);

  /// See [SpotModel.memo].
  static final memo =
      obx.QueryStringProperty<SpotModel>(_entities[1].properties[6]);

  /// See [SpotModel.category].
  static final category =
      obx.QueryStringProperty<SpotModel>(_entities[1].properties[7]);

  /// See [SpotModel.photoPaths].
  static final photoPaths =
      obx.QueryStringVectorProperty<SpotModel>(_entities[1].properties[8]);

  /// See [SpotModel.createdAt].
  static final createdAt =
      obx.QueryDateProperty<SpotModel>(_entities[1].properties[9]);
}

/// [WalkRouteModel] entity fields to define ObjectBox queries.
class WalkRouteModel_ {
  /// See [WalkRouteModel.id].
  static final id =
      obx.QueryIntegerProperty<WalkRouteModel>(_entities[2].properties[0]);

  /// See [WalkRouteModel.uid].
  static final uid =
      obx.QueryStringProperty<WalkRouteModel>(_entities[2].properties[1]);

  /// See [WalkRouteModel.walkSessionId].
  static final walkSessionId =
      obx.QueryStringProperty<WalkRouteModel>(_entities[2].properties[2]);

  /// See [WalkRouteModel.userUid].
  static final userUid =
      obx.QueryStringProperty<WalkRouteModel>(_entities[2].properties[3]);

  /// See [WalkRouteModel.pointsJson].
  static final pointsJson =
      obx.QueryStringProperty<WalkRouteModel>(_entities[2].properties[4]);

  /// See [WalkRouteModel.createdAt].
  static final createdAt =
      obx.QueryDateProperty<WalkRouteModel>(_entities[2].properties[5]);
}

/// [WalkSessionModel] entity fields to define ObjectBox queries.
class WalkSessionModel_ {
  /// See [WalkSessionModel.id].
  static final id =
      obx.QueryIntegerProperty<WalkSessionModel>(_entities[3].properties[0]);

  /// See [WalkSessionModel.uid].
  static final uid =
      obx.QueryStringProperty<WalkSessionModel>(_entities[3].properties[1]);

  /// See [WalkSessionModel.userUid].
  static final userUid =
      obx.QueryStringProperty<WalkSessionModel>(_entities[3].properties[2]);

  /// See [WalkSessionModel.statusName].
  static final statusName =
      obx.QueryStringProperty<WalkSessionModel>(_entities[3].properties[3]);

  /// See [WalkSessionModel.startedAt].
  static final startedAt =
      obx.QueryDateProperty<WalkSessionModel>(_entities[3].properties[4]);

  /// See [WalkSessionModel.finishedAt].
  static final finishedAt =
      obx.QueryDateProperty<WalkSessionModel>(_entities[3].properties[5]);

  /// See [WalkSessionModel.elapsedSeconds].
  static final elapsedSeconds =
      obx.QueryIntegerProperty<WalkSessionModel>(_entities[3].properties[6]);
}
